language: node_js
node_js:
  - "5"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
  - npm install -g webpack
script:
  - npm run lint
  - npm test
after_success:
  - bash .travis/deploy.sh
env:
- NODE_ENV=production
